name: Build Ubuntu Packages 📦

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        description: 'Git ref to build from'
        required: true
        type: string

jobs:
  build-ubuntu-24:
    name: Build Ubuntu 24 Package
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
        fetch-tags: true
        fetch-depth: 0
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git build-essential debhelper dh-python python3-setuptools python3-wheel python3-pip
        sudo apt-get build-dep . -y
        python -m pip install build

    - name: Build Python wheel
      run: |
        python -m build --wheel
    
    - name: Build Debian package
      run: |
        dpkg-buildpackage -us -uc -b
    
    - name: Upload Debian package
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu-24-package
        path: "~/*.deb"

  build-ubuntu-22:
    name: Build Ubuntu 22 Package
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
        fetch-tags: true
        fetch-depth: 0
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git build-essential debhelper dh-python python3-setuptools python3-wheel python3-pip
        sudo apt-get build-dep . -y
        python -m pip install build

    - name: Build Python wheel
      run: |
        python -m build --wheel
    
    - name: Build Debian package
      run: |
        dpkg-buildpackage -us -uc -b
    
    - name: Upload Debian package
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu-22-package
        path: "~/*.deb"
