name: Release

on:
  workflow_dispatch:
  push:
    tags: [ 'v*' ]

jobs:
  build-pypi:
    uses: ./.github/workflows/build-pypi.yml
    with:
      ref: ${{ github.ref }}
    secrets: inherit

  build-debian:
    uses: ./.github/workflows/build-debian.yml
    with:
      ref: ${{ github.ref }}
    secrets: inherit

  create-release:
    name: Create GitHub Release
    needs: [build-pypi, build-debian]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0
    
    - name: Build Changelog
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@v4
      with:
        mode: "HYBRID"
        configurationJSON: |
          {
            "categories": [
              {
                "title": "## 🔄 Changes",
                "labels": []
              }
            ],
            "pr_template": "- #{{TITLE}} (#{{NUMBER}}) by @#{{AUTHOR}}",
            "commit_template": "- #{{TITLE}} (#{{MERGE_SHA}}) by @#{{AUTHOR}}"
          }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: release-artifacts/
        merge-multiple: true
    
    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        gh release create '${{ github.ref_name }}' \
          --repo '${{ github.repository }}' \
          --notes "${{ steps.build_changelog.outputs.changelog }}" \
          release-artifacts/*
