name: Release

on:
  workflow_dispatch:
  push:
    tags: [ 'v*' ]

jobs:
  build-pypi:
    uses: ./.github/workflows/build-pypi.yml
    with:
      ref: ${{ github.ref }}
    secrets: inherit

  build-debian:
    uses: ./.github/workflows/build-debian.yml
    with:
      ref: ${{ github.ref }}
    secrets: inherit

  create-release:
    name: Create GitHub Release
    needs: [build-pypi, build-debian]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0
    
    - name: Build Changelog
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@v4
      with:
        mode: "HYBRID"
        configurationJSON: |
          {
            "categories": [
              {
                "title": "## 🔄 Changes",
                "labels": []
              }
            ],
            "pr_template": "- #{{TITLE}} (#{{NUMBER}}) by @#{{AUTHOR}}",
            "commit_template": "- #{{TITLE}} (#{{MERGE_SHA}}) by @#{{AUTHOR}}"
          }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: release-artifacts/
        merge-multiple: true
    
    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        gh release create '${{ github.ref_name }}' \
          --repo '${{ github.repository }}' \
          --notes "${{ steps.build_changelog.outputs.changelog }}" \
          release-artifacts/*

  publish-to-pypi:
    name: Publish Python 🐍 distribution 📦 to PyPI
    needs: [build-pypi, build-debian]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/tt-smi
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download Python distributions
      uses: actions/download-artifact@v4
      with:
        name: release-dists
        path: dist/

    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

  publish-to-testpypi:
    name: Publish Python 🐍 distribution 📦 to TestPyPI
    needs: [build-pypi, build-debian]
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/tt-smi
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download Python distributions
      uses: actions/download-artifact@v4
      with:
        name: release-dists
        path: dist/
    - name: Publish distribution 📦 to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        verbose: true
